# ns2_python_bridge.py
# --- FINAL VERSION ---

import numpy as np
import subprocess
import os
import time
from typing import Dict

class NS2PythonBridge:
    def __init__(self, simulation_time: float, num_uavs: int, tcl_script: str = 'uav_network.tcl'):
        self.uav_positions = {}
        self.network_metrics = {} 
        self.current_time = 0.0
        self.simulation_time = simulation_time
        self.num_uavs = num_uavs
        self.tcl_script = tcl_script
        self.ns2_process = None
        self.is_running = False
        self.trace_file = 'network.tr' # This file is generated by uav_network.tcl

    def _start_ns2_simulation(self):
        """Starts the NS2 simulation as a subprocess."""
        if not os.path.exists(self.tcl_script):
            print(f"[NS2Bridge] Error: NS2 TCL script '{self.tcl_script}' not found.")
            return
        
        if not os.path.exists('uav_positions'):
            os.makedirs('uav_positions')
            print("[NS2Bridge] Created 'uav_positions' directory.")
        
        if os.path.exists(self.trace_file): os.remove(self.trace_file)
        if os.path.exists('network.nam'): os.remove('network.nam')
        
        try:
            print(f"[NS2Bridge] Starting NS2 simulation: ns {self.tcl_script}")
            self.ns2_process = subprocess.Popen(['ns', self.tcl_script], 
                                                  stdout=subprocess.PIPE,
                                                  stderr=subprocess.PIPE,
                                                  text=True)
            print(f"[NS2Bridge] NS2 process started (PID: {self.ns2_process.pid}).")
            self.is_running = True
            
        except FileNotFoundError:
            print("[NS2Bridge] Error: 'ns' command not found.")
            print("Please ensure NS2 is installed and in your system's PATH.")
            raise
    
    def stop_ns2_simulation(self):
        """Stops the NS2 simulation subprocess."""
        self.is_running = False
            
        if self.ns2_process and self.ns2_process.poll() is None:
            print("[NS2Bridge] Stopping NS2 simulation...")
            self.ns2_process.terminate()
            try:
                self.ns2_process.wait(timeout=5)
                print("[NS2Bridge] NS2 process terminated.")
            except subprocess.TimeoutExpired:
                print("[NS2Bridge] NS2 process did not terminate, killing...")
                self.ns2_process.kill()
        
        if os.path.exists(self.trace_file): 
            os.remove(self.trace_file)

    def update_uav_position(self, uav_id: int, position: np.ndarray, timestamp: float):
        """Update UAV position"""
        self.current_time = timestamp
        position_file = f"uav_positions/uav_{uav_id}_position.txt"
        
        try:
            with open(position_file, 'w') as f:
                f.write(f"{position[0]:.2f} {position[1]:.2f} {position[2]:.2f}")
        except IOError as e:
            print(f"[NS2Bridge] Error writing position file {position_file}: {e}")
        
        self.uav_positions[uav_id] = {'position': position, 'timestamp': self.current_time}
        
    def get_network_metrics(self) -> Dict:
        """
        Parses the 'network.tr' file to get REAL metrics.
        """
        total_sent, total_received, total_dropped = 0, 0, 0
        
        end_time = self.current_time
        start_time = max(0.0, end_time - 5.0) # 5-second sliding window

        try:
            with open(self.trace_file, 'r') as f:
                for line in f:
                    parts = line.split()
                    
                    # --- PARSER FIX ---
                    if len(parts) < 7:
                        continue
                    
                    event_type = parts[0]
                    event_time = float(parts[1])
                    trace_level = parts[3] # Column 3 is 'AGT'
                    # --- END OF FIX ---

                    if event_time < start_time:
                        continue
                    if event_time > end_time:
                        break 
                        
                    if trace_level == "AGT":
                        # --- PARSER FIX ---
                        packet_type = parts[6] # Column 6 is 'cbr'
                        # --- END OF FIX ---
                        
                        if packet_type == "cbr":
                            if event_type == "s":
                                total_sent += 1
                            elif event_type == "r":
                                total_received += 1
                            elif event_type == "d":
                                total_dropped += 1
                                
        except FileNotFoundError:
            pass
        except Exception as e:
            print(f"[NS2Bridge] Error parsing trace file: {e}")

        self.network_metrics[int(end_time)] = {
            'sent': total_sent,
            'recv': total_received,
            'drop': total_dropped
        }
        
        pdr = total_received / max(total_sent, 1)
        
        return {
            'packet_delivery_ratio': pdr,
            'packet_loss_ratio': total_dropped / max(total_sent, 1),
            'throughput': total_received / 5.0 
        }
