# uav_network.tcl
# --- This script is run by NS2 ---
# It defines the simulation, creates UAV nodes, sets up routing and traffic,
# and reads position files generated by the Python controller.

# --- 1. Simulation Parameters ---
set val(chan)       Channel/WirelessChannel
set val(prop)       Propagation/TwoRayGround
set val(netif)      Phy/WirelessPhy
set val(mac)        Mac/802_11
set val(ifq)        Queue/DropTail/PriQueue
set val(ll)         LL
set val(ant)        Antenna/OmniAntenna
set val(ifqlen)     50                     ;# max packet in ifq
set val(nn)         5                      ;# number of UAV nodes
set val(rp)         AODV                   ;# routing protocol
set val(stop)       100.0                  ;# simulation duration (matches Python)

# --- 2. Simulation Setup ---
set ns [new Simulator]
set tracefd [open network.tr w]
set namfd [open network.nam w]

$ns trace-all $tracefd
$ns namtrace-all $namfd

# Set up topography
set topo [new Topography]
# Define a 3D area. Z-dimension is used for wireless propagation.
$topo load_flatgrid 1000 1000

# Create God object
create-god $val(nn)

# --- 3. Wireless Node Configuration ---
$ns node-config -adhocRouting $val(rp) \
                -llType $val(ll) \
                -macType $val(mac) \
                -ifqType $val(ifq) \
                -ifqLen $val(ifqlen) \
                -antType $val(ant) \
                -propType $val(prop) \
                -phyType $val(netif) \
                -channel [new $val(chan)] \
                -topoInstance $topo \
                -agentTrace ON \
                -routerTrace ON \
                -macTrace OFF \
                -movementTrace ON

# --- 4. Create UAV Nodes ---
for {set i 0} {$i < $val(nn)} {set i [expr $i + 1]} {
    set node_($i) [$ns node]
    $node_($i) random-motion 0 ;# Disable random motion
    
    # Set initial positions (Python will override this quickly)
    set X [expr $i * 50 + 50]
    set Y [expr $i * 50 + 50]
    set Z 100
    $node_($i) set X_ $X
    $node_($i) set Y_ $Y
    $node_($i) set Z_ $Z
}

# --- 5. Define Network Traffic (CBR) ---
# This is the CRITICAL part for PDR=0
# We will create CBR traffic from UAV 0 to UAV 1
set udp [new Agent/UDP]
$ns attach-agent $node_(0) $udp

set cbr [new Application/Traffic/CBR]
$cbr set packetSize_ 512
$cbr set interval_ 0.2 ;# 5 packets per second
$cbr attach-agent $udp

set null [new Agent/Null]
$ns attach-agent $node_(1) $null

$ns connect $udp $null

# Start traffic 1 second into the simulation
$ns at 1.0 "$cbr start"
$ns at $val(stop) "$cbr stop"


# --- 6. Position Update Procedure ---
# This procedure reads the position file for a single UAV
proc update_position {uav_id} {
    global ns node_
    
    set file_name "uav_positions/uav_${uav_id}_position.txt"
    
    # Check if the file exists
    if { [file exists $file_name] } {
        set f [open $file_name r]
        set data [read $f]
        close $f
        
        # Parse the "X Y Z" string
        if { [llength $data] == 3 } {
            set X [lindex $data 0]
            set Y [lindex $data 1]
            set Z [lindex $data 2]
            
            # Update the node's position in the NS2 simulator
            $node_($uav_id) set X_ $X
            $node_($uav_id) set Y_ $Y
            $node_($uav_id) set Z_ $Z
        }
    }
}

# --- 7. Schedule Position Updates ---
# This procedure runs every 1 second (matches Python)
proc schedule_updates {} {
    global ns val
    
    set update_interval 1.0
    
    for {set i 0} {$i < $val(nn)} {set i [expr $i + 1]} {
        update_position $i
    }
    
    # Reschedule itself
    set now [$ns now]
    if { $now < $val(stop) } {
        $ns at [expr $now + $update_interval] "schedule_updates"
    }
}

# Start the first update check 1 second in
$ns at 1.0 "schedule_updates"


# --- 8. Simulation Start/Stop ---
# Define stop procedure
proc finish {} {
    global ns tracefd namfd
    $ns flush-trace
    close $tracefd
    close $namfd
    puts "NS2 Simulation Finished."
    exit 0
}

$ns at $val(stop) "finish"
puts "Starting NS2 Simulation..."
$ns run
